In [2]:
#Code by Anubhav Natani

In [3]:
#importing tensorflow

In [4]:
import tensorflow as tf

/home/anubhav/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


tensorflow works on the computational graph model

making a basic tensor flow graph

In [5]:
#this type of operations are called source operation
#they do not need any computation
a = tf.constant([2])
b = tf.constant([3])

In [6]:
#this is a computation operation
c = tf.add(a,b)

In [7]:
#we need a session to run tensorflow operations
session = tf.Session()

In [8]:
result = session.run(c)
print(result)

[5]


In [9]:
#closing the session
session.close()

In [10]:
#other way of doing the same effectively
with tf.Session() as sess:
    result = sess.run(c)
    print(result)

[5]


In [11]:
#we can visualize the graph we made using tensorboard
writer = tf.summary.FileWriter("./graphs",tf.get_default_graph())

In [12]:
#as every thing is needed to run in tensorflow session so this too is needed to learn in tensorflow session
with tf.Session() as sess:
    print(sess.run(c))
#we need to close the writer
writer.close()

[5]


 To see the computational graph in tensorboard
 we need to open the terminal and type

 if running jupyter notebook
 
 tensorboard --logdir="./graphs" --port 6006

 else
 
 python3 pythonprogram.py
 
 tensorboard --logdir="./graphs" --port 6006   

In [13]:
#we need to reset our graph to clean it 
tf.reset_default_graph

<function tensorflow.python.framework.ops.reset_default_graph>

In [14]:
#tensor basically means multidimensional array
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session() as session:
    result = session.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = session.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = session.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = session.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 [2] 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



 Some matrix or tensor operation in tensorflow

In [15]:
#it is element wise multiplication of the numbers in the matrix
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)
second_operation = Matrix_one + Matrix_two

with tf.Session() as session:
    result = session.run(first_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = session.run(second_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Defined using normal expressions :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


In [16]:
#Regular matrix multiplication
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one, Matrix_two)

with tf.Session() as session:
    result = session.run(first_operation)
    print ("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[13 18]
 [18 25]]


# Variables

We can also make variables with tensorflow

In [17]:
ab = tf.Variable(7)
one = tf.constant(1)
new_value = tf.add(ab,one)
update = tf.assign(ab,new_value)

In [20]:
#variables must be initialized before using 
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    sess.run(update)
    print(sess.run(ab))

8


In [22]:
#there is a common convention of writing for loops 
with tf.Session() as sess:
    sess.run(init_op)
    for _ in range(3):
        sess.run(update)
        print(sess.run(ab))

8
9
10


# Place Holders

In [25]:
a = tf.placeholder(tf.float32)
b = a*2
#now we can pass the data in the place of a when we are running the session 
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print(result)

7.0


In [27]:
dictionary = {a:[1,2,3]}
with tf.Session() as sess:
    result=sess.run(b,feed_dict=dictionary)
    print(result)

[2. 4. 6.]


In [28]:
#this concludes the basic of tensorflow there are many operation in tensorflow documentation which we can see.

----------Code contributed by Anubhav Natani-----------